### PR TITLE
Fix install on FreeBSD

### PR DESCRIPTION
**Pull request by slegrand45**
This pull request updates the generated OASIS files to version 0.4.6 and also includes the configure patch to fix the installation on FreeBSD (see https://github.com/ocsigen/macaque/issues/39).

### CODE REVIEW

**Comment by vasilisp** [comment]
Can you provide a bit more info on the failure? I have used Eliom and its dependencies on FreeBSD in the recent past, and I don't remember any trouble with `deriving`. In contrast, I needed a small fix for OpenBSD (c87ae925eaabddcff3a973a2db8ca36a08dde33b).

Also, do things work if you run OASIS as `oasis setup -setup-update dynamic`? I find committing and distributing the huge OASIS-generated files quite messy.

**Comment by slegrand45** [comment]
I have the following failure:
```sh
% opam pin add deriving --dev-repo
deriving is now git-pinned to https://github.com/ocsigen/deriving.git

[deriving] https://github.com/ocsigen/deriving.git updated
[deriving] Installing new package description from https://github.com/ocsigen/deriving.git

deriving needs to be installed.
The following actions will be performed:
  ∗  install   deriving    dev* 
  ↻  recompile js_of_ocaml 2.7                [uses deriving]
  ↻  recompile gen_js_api  1.0.1              [uses js_of_ocaml]
===== ∗  1   ↻  2 =====
Do you want to continue ? [Y/n] y

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[gen_js_api] Archive in cache
[js_of_ocaml] Archive in cache
[deriving] https://github.com/ocsigen/deriving.git already up-to-date

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
⊘  removed   gen_js_api.1.0.1
[ERROR] The compilation of deriving failed at "./configure --prefix /home/stephane/.opam/4.03.0 --enable-tc".
⊘  removed   js_of_ocaml.2.7
Processing  3/5: [deriving: ocamlfind remove]
#=== ERROR while installing deriving.dev ======================================#
# opam-version 1.2.2
# os           freebsd
# command      ./configure --prefix /home/stephane/.opam/4.03.0 --enable-tc
# path         /home/stephane/.opam/4.03.0/build/deriving.dev
# compiler     4.03.0
# exit-code    2
# env-file     /home/stephane/.opam/4.03.0/build/deriving.dev/deriving-23614-d8a4ae.env
# stdout-file  /home/stephane/.opam/4.03.0/build/deriving.dev/deriving-23614-d8a4ae.out
# stderr-file  /home/stephane/.opam/4.03.0/build/deriving.dev/deriving-23614-d8a4ae.err
### stdout ###
# 
# make: stopped in /sequoia/.opam/4.03.0/build/deriving.dev
### stderr ###
# make: don't know how to make ./setup.exe. Stop
```

And if i try `oasis setup -setup-update dynamic` and the configure patch, i get:
```sh
=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[ERROR] The compilation of deriving failed at "./configure --prefix /home/stephane/.opam/4.03.0 --enable-tc".
Processing  1/1: [deriving: ocamlfind remove]
#=== ERROR while installing deriving.dev ======================================#
# opam-version 1.2.2
# os           freebsd
# command      ./configure --prefix /home/stephane/.opam/4.03.0 --enable-tc
# path         /home/stephane/.opam/4.03.0/build/deriving.dev
# compiler     4.03.0
# exit-code    1
# env-file     /home/stephane/.opam/4.03.0/build/deriving.dev/deriving-24095-5f1023.env
# stdout-file  /home/stephane/.opam/4.03.0/build/deriving.dev/deriving-24095-5f1023.out
# stderr-file  /home/stephane/.opam/4.03.0/build/deriving.dev/deriving-24095-5f1023.err
### stderr ###
# File "setup.ml", line 26, characters 5-16:
# Error: Unbound module OASISDynRun
# File "setup.ml", line 26, characters 5-16:
# Error: Unbound module OASISDynRun
```

**Comment by vasilisp** [comment]
Unfortunately, your PR causes trouble on Linux, [as per the CI failure](https://ci.inria.fr/ocsigen/job/Deriving-4.02.1-PR/68/console). So I would suggest sticking to dynamic update. 

I tested two approaches: a slightly updated patch for the configure script (c0d6b893358b15ff2baafa1985123a9089878e8f), and an OPAM configuration that circumvents the configure script (d0c71946ee9c3ad3576d468a7d5447150f1db681). Both work on a fresh FreeBSD EC2 instance. I somewhat prefer the second approach, because it doesn't mess with auto-generated files. Opinions?

**Comment by slegrand45** [comment]
As my aim is to be able to use OPAM to install deriving, if a patch to the OPAM configuration file has your preference, it's perfectly fine for me.

**Comment by vasilisp** [comment]
I merged the OPAM patch. We can also fix 0.7.1 in `opam-repository` in the same way.

Feel free to complain for any Ocsigen installation trouble on *BSD :).

**Comment by slegrand45** [comment]
Thank you very much. I will certainly complain again if needed :smiley:

Regarding the fix in `opam-repository` for 0.7.1, do i send the pull request or do you prefer to do it?

**Comment by vasilisp** [comment]
Go ahead if you volunteer :). The OPAM files in `opam-repository` and in `ocsigen/deriving` have slightly diverged if I remember correctly; start from the one in `opam-repository` and modify the sequence of commands. Thanks!

**Comment by slegrand45** [comment]
The OPAM repository has been updated for version 0.7.1.

**Pull request closed without merging**
